apiVersion: v1
kind: Secret
metadata:
  name: scylla-agent-config
stringData:
  scylla-manager-agent.yaml: |
    s3:
      access_key_id: 9b8b55e49d56dc3bd0d8fd3a439aeed3609d9884
      secret_access_key: <redacted>
      endpoint: https://ax3dvr7ymlov.compat.objectstorage.us-sanjose-1.oraclecloud.com
      provider: Other
